version: 3

tasks:
  default:
    cmds:
      - nodemon -q -e 'go' --signal SIGTERM --exec "echo '# building' && task build && echo '# build success' && task run || exit"

  build:
    cmds:
      - go build -o bin/app .

  run:
    cmds:
      - ./bin/app -mode=client -proxyAddr=192.168.13.254:4455 -serverAddr=gcp-dev.kloudlite.io:32000
  

  docker:build:local:
    cmds:
      - docker build -t ghcr.io/abdheshnayak/go-tunnel:v1.0.0 .

  docker:push:
    preconditions:
      - sh: '[[ -n "{{.tag}}" ]]'
        msg: "var tag must have a value, of format 'v1.0.0-nightly'"
    cmds:
      - docker buildx build --build-arg VERSION={{.tag}} -t ghcr.io/abdheshnayak/go-tunnel:{{.tag}} . --push

